<script setup lang="ts">
import RetargetLabDashboard from './RetargetLabDashboard.vue';
import type { RetargetLabProps } from './retargetLabProps';
import { useRetargetLabController } from './useRetargetLabController';

const props = defineProps<RetargetLabProps>();

const lab = useRetargetLabController(props);
</script>

<template>
  <RetargetLabDashboard
    v-model:info-modal-open="lab.infoModalOpen"
    v-model:preset-name="lab.presetName"
    v-model:selected-preset-id="lab.selectedPresetId"
    v-model:mapping-view="lab.mappingView"
    v-model:selected-bone="lab.selectedQuatBone"
    v-model:quaternion-mode="lab.quaternionMode"
    v-model:correction-mode="lab.correctionMode"
    v-model:preview-time="lab.previewTime"
    v-model:quat-preset-name="lab.quatPresetName"
    v-model:selected-quat-preset-id="lab.selectedQuatPresetId"
    :current-file="lab.currentFile"
    :analysis="lab.analysis"
    :source-origin="lab.sourceOrigin"
    :context-source-label="lab.contextSourceLabel"
    :preview-status-label="lab.previewStatusLabel"
    :active-correction-count="lab.activeCorrectionCount"
    :last-import-message="lab.lastImportMessage"
    :mapped-count="lab.mappedCount"
    :slot-count="lab.slotCount"
    :error="lab.error"
    :presets="lab.presets"
    :selected-preset="lab.selectedPreset"
    :source-preview="lab.sourcePreview"
    :target-preview="lab.targetPreview"
    :original-compare-preview="lab.originalComparePreview"
    :corrected-compare-preview="lab.correctedComparePreview"
    :mapping-view-options="lab.mappingViewOptions"
    :visible-slots="lab.visibleRetargetSlots"
    :source-options="lab.sourceOptions"
    :mapping="lab.mapping"
    :loading="lab.loading"
    :importing="lab.importing"
    :required-missing-count="lab.requiredMissing.length"
    :target-joints="lab.targetJoints"
    :can-import="lab.canImport"
    :selected-quat-preset="lab.selectedQuatPreset"
    :quat-presets="lab.quatPresets"
    :quaternion-mode-options="lab.quaternionModeOptions"
    :correction-mode-options="lab.correctionModeOptions"
    :quat="lab.quat"
    :euler-deg="lab.eulerDeg"
    :axis-angle="lab.axisAngle"
    :corrections="lab.quaternionCorrections"
    :preview-mode="lab.previewMode"
    :previewing="lab.previewing"
    :can-preview="lab.canPreview"
    :preview-name="lab.previewName"
    :preview-duration="lab.previewDuration"
    :summary-rows="lab.reportSummary"
    :quaternion-rows="lab.currentQuaternionRows"
    :mapping-rows="lab.reportMappingRows"
    @analyze-file="(file) => lab.analyze(file, 'manual')"
    @back-to-player="lab.goBackToPlayer"
    @save-preset="lab.savePreset"
    @load-preset="lab.loadSelectedPreset"
    @delete-preset="lab.deleteSelectedPreset"
    @export-preset="lab.exportSelectedPreset"
    @import-preset-file="lab.importPresetFile"
    @auto-mapping="lab.restoreAutoMapping"
    @clear-mapping="lab.clearMapping"
    @mapping-change="lab.updateMapping"
    @bone-change="lab.syncQuatFromBone"
    @quat-field-change="lab.updateQuatField"
    @euler-field-change="lab.updateEulerField"
    @axis-angle-field-change="lab.updateAxisAngleField"
    @read-quaternion="lab.syncQuatFromBone"
    @apply-quaternion="lab.applyQuaternionToBone"
    @normalize-quaternion="lab.normalizeQuaternionEditor"
    @identity-quaternion="lab.identityQuaternion"
    @invert-quaternion="lab.invertQuaternion"
    @copy-quaternion-json="lab.copyQuaternionJson"
    @paste-quaternion-json="lab.pasteQuaternionJson"
    @add-correction="lab.addQuaternionCorrection"
    @clear-corrections="lab.clearQuaternionCorrections"
    @toggle-correction="lab.toggleQuaternionCorrection"
    @remove-correction="lab.removeQuaternionCorrection"
    @preview="lab.previewCurrent"
    @seek-preview="lab.seekPreview"
    @stop-preview="lab.stopPreview"
    @save-quat-preset="lab.saveQuatPreset"
    @load-quat-preset="lab.loadQuatPreset"
    @delete-quat-preset="lab.deleteQuatPreset"
    @import-current="lab.importCurrent"
    @copy-report="lab.copyRetargetInfo"
  />
</template>
